### ISSUE TITLE
Problem creating two connections

### ISSUE THREAD

**Issue by mattwg** [baztian/jaydebeapi#1]
I am struggling to create two connections in a single python program.  My use case is that I want to connect to a source database and a target database to move data around.  My single program requires both connections to be live at the same time. I am trying to run this code in Python 2.7.5:

```
    import jaydebeapi as jdbc

    ct = jdbc.connect('com.teradata.jdbc.TeraDriver',
                     ['jdbc:teradata://vivaldi.vip.ebay.com', getpass.getuser(), p[0]],
                     ['/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ebaytd/terajdbc4.jar',
                      '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/ebaytd/tdgssconfig.jar'],)

    cm = jdbc.connect('com.mysql.jdbc.Driver',
                    ['jdbc:mysql://10.9.250.213:3306','root',p[0]],
                    ['/Users/magardner/Documents/Development/R/mysqljdbc/mysql-connector-java-5.1.33-bin.jar'],)
```

I get an error when the second call to jdbc.connect is made:

```
Traceback (most recent call last):
  File "/Users/magardner/PycharmProjects/ebayep-backend/process.py", line 82, in <module>
    main()
  File "/Users/magardner/PycharmProjects/ebayep-backend/process.py", line 61, in main
    ['/Users/magardner/Documents/Development/R/mysqljdbc/mysql-connector-java-5.1.33-bin.jar'],)
  File "/Users/magardner/untitled/lib/python2.7/site-packages/jaydebeapi/dbapi2.py", line 269, in connect
    jconn = _jdbc_connect(jclassname, jars, libs, *driver_args)
  File "/Users/magardner/untitled/lib/python2.7/site-packages/jaydebeapi/dbapi2.py", line 116, in _jdbc_connect_jpype
    jpype.JClass(jclassname)
  File "/Users/magardner/untitled/lib/python2.7/site-packages/jpype/_jclass.py", line 58, in JClass
    raise _RUNTIMEEXCEPTION.PYEXC("Class %s not found" % name)
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class com.mysql.jdbc.Driver not found
```

However if I comment out _either_ of the jdbc.connect statements each runs successfully on it's own and allows me to connect to the relevant database.  If I reverse the order of the jdbc.connect statements I still get the error on the second call.

I think this may have something to do with the way that JPype is being reused in the second call.  Is this something I am doing wrong?  Or is there a known issue here? 

Thanks in advance for any suggestions,
Matt

**Comment by pybokeh** [comment]
This issue is a life saver!  I was having the same issue and couldn't figure out why for the longest time.  Now I know!  I agree that a warning is needed for this.
