### ISSUE TITLE
works with Teradata Aster

### ISSUE THREAD

**Issue by jkomn** [baztian/jaydebeapi#10]
Hi, I just wanted to let you know that jaydebeapi works fine for me with Aster. I'm using Aster Express virtual machines and connect from Python3 on Windows 7. Thank you for your work on jaydebeapi!

If you are interested in the code I use, I paste it in the following:

    import jpype,jaydebeapi
    
    def connectExpress(database='beehive',user='beehive',password='beehive'):
        # from TD Studio Default Driver definition
        jclassname='com.asterdata.ncluster.Driver'
        # from TD Studio jdbc:<subprotocol>://<server>:<port>/<database>
        url='jdbc:ncluster://192.168.100.100:2406/'+database
        # driver args contains the arguments passed to java: DriverManager.getConnections(...)
        # see http://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html#getConnection(java.lang.String,%20java.lang.String,%20java.lang.String)
        driver_args=[url,user,password]
        # jar: use it as argument in jpype.startJVM
        asterjar='C:/Program Files/Teradata/clients-win64/noarch-aster-jdbc-driver.jar'
        jvmstartargs='-Djava.class.path='+asterjar
        
        # start JVM if not running yet (in the 64bit version the client JVM was removed, so use the server JVM instead)
        if not jpype.isJVMStarted():
            jpype.startJVM(r'C:\Program Files\Java\jre7\bin\server\jvm.dll',jvmstartargs)
        # establish connection
        return jaydebeapi.connect(jclassname,driver_args)

**Comment by baztian** [comment]
Thanks for letting me know. Glad you appreciate the work on jaydebeapi. :)

Is Aster something different than Teradata DB? If so I should add it to the supported databases section of the README.

One tip for you how you can simplify your code:

    import jaydebeapi
    
    def connectExpress(database='beehive',user='beehive',password='beehive'):
        # from TD Studio Default Driver definition
        jclassname='com.asterdata.ncluster.Driver'
        # from TD Studio jdbc:<subprotocol>://<server>:<port>/<database>
        url='jdbc:ncluster://192.168.100.100:2406/'+database
        # driver args contains the arguments passed to java: DriverManager.getConnections(...)
        # see http://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html#getConnection(java.lang.String,%20java.lang.String,%20java.lang.String)
        driver_args=[url,user,password]
        asterjar='C:/Program Files/Teradata/clients-win64/noarch-aster-jdbc-driver.jar'
        return jaydebeapi.connect(jclassname, driver_args, asterjar)

You shouldn't need direct JPype interaction.

**Comment by jkomn** [comment]
Yes, Aster is different, and it focuses on Data Discovery. It was previously independent and is now a product of Teradata, so in the upcoming versions the interfaces between Teradata DB and Aster will be further improved, but as far as i know they will remain independent products.

Thank you for your tip! The only problem is that jpype.getDefaultJVMPath() returns a non-existing jvm_path on my system. I'll see if I can find a solution for that.

**Comment by baztian** [comment]
Regarding jpype.getDefaultJVMPath(): You could set the JAVA_HOME environment variable. Then Jpype should be able to find the default jvm path automatically. It should be able to find it anyway. Please consider reporting a JPype bug.

If the JAVA_HOME thing works for you, you could also set CLASSPATH environment variable. Then you can leave the `asterjar` variable off and don't need hard coded paths in your code.

**Comment by jkomn** [comment]
Thank you for suggesting the use of the CLASSPATH environment variable, it works for me.

Regarding jpype.getDefaultJVMPath() JAVA_HOME did not help. However, I checked what it does in detail and found out that the registry key it accesses was wrong (...\client\jvm.dll, but on 64bit Windows 7 only ...\server\jvm.dll exists, at least on my machine). Fixing this solved the issue.
