### ISSUE TITLE
Jpype 0.7 report this warning

### ISSUE THREAD

**Issue by manuelvalino** [baztian/jaydebeapi#109]
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.

**Comment by kimehta** [comment]
https://github.com/baztian/jaydebeapi/issues/99

**Comment by baztian** [comment]
Should be fixed in the current version
