### ISSUE TITLE
Release a new version to pypi

### ISSUE THREAD

**Issue by thebestnom** [baztian/jaydebeapi#117]
I saw that you have a lot of commits since the last pypi release, any thing that hold you back from releasing a new version?

**Comment by baztian** [comment]
Thanks @thebestnom for pointing out. For several reasons the build process is currently broken. I try to have another look on it in a couple of weeks.

**Comment by Thomas-Brandl** [comment]
really looking forward to the new version as well!

**Comment by ofek** [comment]
@baztian Is there anything we can do to help? Many of us require a new release to PyPI.

**Comment by jakubjedelsky** [comment]
Hello,

Fedora package maintainer here, could I ask you also for release the version 1.1.2 also on the github itself? It will be much more easier to grab it from https://github.com/baztian/jaydebeapi/releases page instead of source code itself.

**Comment by ofek** [comment]
@baztian Any updates?

**Comment by jstoja** [comment]
@baztian if you could point us to items that you know need fixing to make the build pass again, that would maybe help some of us try to fix the pipeline.
I've tried to run them locally but didn't succeed.

**Comment by baztian** [comment]
Thanks @jstoja, that's very nice.
What kind of issues were you facing locally when you try to run the tests?

Currently https://github.com/jythontools/jython/issues/160 is one issue and the other was [pointed out](https://github.com/baztian/jaydebeapi/pull/108#issuecomment-509808777) by @Thrameos: There is probably a bug in [a line in JPype](https://github.com/jpype-project/jpype/blob/69060be7f2624711c94fdd0d60c868df1ef5ed69/jpype/_jexception.py#L65). I didn't find the time to verify, write a failing unit test for JPype and open a pull request with the fix.

If it's just about the release I could in theory deploy manually to pypi. But for me that feels kind of strange and I would rather prefer to have a working build pipeline and a proof that everything is working well again first.

**Comment by albertvaka** [comment]
Any update on this?

**Comment by baztian** [comment]
Just released a new version to PyPI.
