### ISSUE TITLE
Catch Netezza database errors

### ISSUE THREAD

**Issue by JWDobken** [baztian/jaydebeapi#123]
I run sql commands on a Netezza db with Python using [JayDeBeApi](https://pypi.org/project/JayDeBeApi/). While inserting many records with a single insert command, validation errors by the database are passed in silence.

**Minimal example to reproduce**

Here is a sql table created with two columns (FAVCOLOR and NAME), the last record contains an integer instead of a string:

```python
import jaydebeapi

database_url = 'jdbc:netezza://NETEZZAIPADDRESS:5480/NZDATABASE'
jclassname='org.netezza.Driver'
username='MYUSERNAME'
password='MYPASSWORD'

sql = """
DROP TABLE MYSCHEMA.WEIRDPERSONS IF EXISTS;
CREATE TABLE IF NOT EXISTS MYSCHEMA.WEIRDPERSONS (FAVCOLOR VARCHAR(7), NAME VARCHAR(40));
INSERT INTO MYSCHEMA.WEIRDPERSONS (FAVCOLOR, NAME)
SELECT '#471934','Wayne Baker' UNION ALL
SELECT '#debf8e','Kenneth Holmes' UNION ALL
SELECT '#a921dd','Richard Taylor' UNION ALL
SELECT 1,'Linda Roberson';
"""

con = jaydebeapi.connect(
            jclassname=jclassname,
            url=database_url,
            driver_args=[username, password])
cursor = con.cursor()
cursor.execute(sql)
con.close()
```

The table will be empty since the insert command fails on validation.

**what I expect**

I expect the cursor execution to raise a Netezza DatabaseError

**Comment by baztian** [comment]
Neither Java JDBC nor Python DB API are designed to execute multiple statement with one execute call. You have to iterate over the lines of `sql` and call `execute()` for each of them.
