### ISSUE TITLE
Non handled exception

### ISSUE THREAD

**Issue by rene-bakker-it** [baztian/jaydebeapi#126]
Symptom: raising an exception on line 151 of `__init__.py` of this package
> TypeError: issubclass() arg 1 must be a class

The exception is raised when running an erroneous SQL against a MySQL, MS SqlServer, or Oracle jdbc connection. I am running it in development with:

- Linux Mint 19.2 Tina
- openjdk version "1.8.0_222"
- Python 3.6.7, clean virtualenv 
- JPype1, version 0.7.0
- JayDeBeApi, version 1.1.2
- jdbc drivers: mysql-connector-java-5.1.39.jar, ojdbc8.jar, and  mssql-jdbc-6.3.5.jre8-preview.jar

  
The error is avoided if I change lite 151 of `__init__.py` 
from:
> `if issubclass(exc_info[1].__javaclass__, SQLException):`

into: 
> `if issubclass(exc_info[1].__class__, SQLException):`

In that case I get the expected SQL error, e.g., ORA-00942: table or view does not exist

If this is a know issue, please excuse me for bothering you.

**Comment by baztian** [comment]
Can you verify if this is still an issue with the most recent JayDeBeApi release?

**Comment by baztian** [comment]
Should be fixed by #135
