### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by cgivre** [baztian/jaydebeapi#127]
I am very appreciative of JayDeBeApi, but is there any plan on releasing updates to Pypi?  Particularly, the fixes for Jpype v 0.7?

Theses issues are blocking a project I'm working on, and if there is anything I can do to assist, please let me know.

**Comment by baztian** [comment]
Thank you for offering me some help. Please see #117. I pointed out the issues and the places where help would be greatly appreciated.
