### ISSUE TITLE
Incorrect datetime as str

### ISSUE THREAD

**Issue by nrcharles** [baztian/jaydebeapi#13]
I'm interacting with snowflake computing database using python connecting via jaydebeapi and the JDBC driver.

In the database I have a TIMESTAMP_LTZ(9) field containing Sat, 01 Nov 2014 07:49:46 -0700 which is localized to a python str  '2014-11-01 10:45:49'  which is Eastern Timezone, time zone my computer is in.  

Is this date getting localized to EST in jaydebeapi? Secondly, is that where it's getting flattened to a string?

**Comment by baztian** [comment]
I've never worked with that database. It depends on the JDBC Driver how this gets mapped in jaydebeapi.
If it is bound to the JDBC type `java.sql.Types.TIMESTAMP` it gets converted using the method _to_datetime in https://github.com/baztian/jaydebeapi/blob/master/jaydebeapi/__init__.py 

If you need special type handling you can do it like this: http://stackoverflow.com/a/27030314/1960601 (this is not officially supported and might get changed in future versions). Please report the solution you came up with. I'm willing to  improve jaydebeapi if there is a better way for date and timestamp handling.

**Comment by nrcharles** [comment]
It turns out my issue was due to the JDBC driver localizing the data. The
work around was add use the to_char() function so the returned timestamp
value was returned as a string and not localized.

On Wed, Sep 16, 2015 at 11:09 AM, baztian <notifications@github.com> wrote:

> I've never worked with that database. It depends on the JDBC Driver how
> this gets mapped in jaydebeapi.
> If it is bound to the JDBC type java.sql.Types.TIMESTAMP it gets
> converted using the method *to_datetime in
> https://github.com/baztian/jaydebeapi/blob/master/jaydebeapi/__init_
> <https://github.com/baztian/jaydebeapi/blob/master/jaydebeapi/__init_>*.py
>
>
> If you need special type handling you can do it like this:
> http://stackoverflow.com/a/27030314/1960601 (this is not officially
> supported and might get changed in future versions). Please report the
> solution you came up with. I'm willing to improve jaydebeapi if there is a
> better way for date and timestamp handling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baztian/jaydebeapi/issues/13#issuecomment-140771228>.
>



-- 
Nathan Charles
http://www.char1es.net

**Comment by baztian** [comment]
So this issues is resolved? Anything jaydebeapi could have done better in your opinion?

**Comment by nrcharles** [comment]
This issue is resolved. jaydebeapi was returning a str instead of datetime,
which was unexpected behavior and that made me suspect jaydebeapi, but the
issue was coming from the JDBC driver. From that perspective, I think there
is a gap between jaydebeapi and JDBC, but I don't have a suggestion of how
it would be improved.

On Wed, Sep 16, 2015 at 11:15 AM, baztian <notifications@github.com> wrote:

> So this issues is resolved? Anything jaydebeapi could have done better in
> your opinion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/baztian/jaydebeapi/issues/13#issuecomment-140772977>.
>



-- 
Nathan Charles
http://www.char1es.net

**Comment by baztian** [comment]
Ok, thanks for the feedback. You expected to get a datetime. Some python db drivers work the way that you get a datetime by default others have str as default. Probably it would be nice to have a solid way to configure it or write adapters like [the sqlite driver allows](https://docs.python.org/2/library/sqlite3.html#default-adapters-and-converters).

In the meantime you could try the following snippet before calling the connect method. This should give you datetime objects for JDBC TIMESTAMP types. It is basically the existing behaviour but without the str conversion.

    import jaydebeapi
    from jaydebeapi import _DEFAULT_CONVERTERS
    def _to_datetime(rs, col):
        java_val = rs.getTimestamp(col)
        if not java_val:
            return
        d = datetime.datetime.strptime(str(java_val)[:19], "%Y-%m-%d %H:%M:%S")
        return d.replace(microsecond=int(str(java_val.getNanos())[:6]))
    _DEFAULT_CONVERTERS.update({'TIMESTAMP': _to_datetime})

**Comment by alexnasz** [comment]
2021-10-18 14:48:19.047 is converted to 2021-10-18 14:48:19.470000 so there is a still bug, it should be 2021-10-18 14:48:19.047000

The fix for that is to pad with 0 from left with following expression:

d.replace(microsecond=int(f"{java_val.getNanos():0>9}"[:6]))
