### ISSUE TITLE
Support "with" statement (PEP 343)

### ISSUE THREAD

**Issue by Szczepanov** [baztian/jaydebeapi#138]
Add support to use Connection and Cursor objects in the "with" statement
with jaydebeapi.connect( ... ) as conn:
    with conn.cursor() as cursor:
        # run some commands

I currently get an AttributeError: __enter__

The remedy is to add to Cursor and Connection classes __enter__ method and an __exit__ method which closes the resource.

**Comment by Szczepanov** [comment]
https://github.com/baztian/jaydebeapi/pull/139

**Comment by baztian** [comment]
Thanks for the PR!
