### ISSUE TITLE
Is There Any Way to set timeout on jaydebeapi execute?

### ISSUE THREAD

**Issue by panickery** [baztian/jaydebeapi#157]
conn = jaydebeapi.connect(
           conf_dict['jdbc_driver_class'],`
           conf_dict['jdbc_connection_string'],
           [db_id, db_pw],     
           conf_dict['jdbc_driver_library'] )

        logging.debug('CONNECT_SUCCESS!')
        cur = conn.cursor()
        logging.debug('BEFORE EXECUTE!')
        logging.debug('EXECUTE QUERY :: {}'.format(query))
        cur.execute(query)
        logging.debug('AFTER EXECUTE!')  <-- not printed

I always thanks for jaydebeapi.
above code is in my script
most time this script works well, but some big query doen'st work well
query execute never ends and the process of python script too.
so I want set timeout to execute, How can i set timeout on 'execute'?
thank you

**Comment by baztian** [comment]
Usually there are system parameters you can set depending on the JDBC driver/vendor. Are you using the Jaydebeapi on CPython or on Jython? To be able to pass system parameters you currently have to start JPype beforehand. This way you can add commandline args if I remember correctly using '-Dkey=value'. Once #116 has been properly integrated this could be added to the connect method.

Another approach would be JDBC 4.1. But this isn't supported directly by JayDeBeApi either at the moment. https://stackoverflow.com/questions/18822552/setting-network-timeout-for-jdbc-connection might give you some more detail on that.

**Comment by panickery** [comment]
Thank you For the answer.
I'm using Python and your answer is quite helpful.
