### ISSUE TITLE
connect to db using properties

### ISSUE THREAD

**Issue by testlnord** [baztian/jaydebeapi#16]
Method getConnection of DriverManager class can be called with Properties as second argument. It's very comfortable and allows to send more parameters to driver than just name and password.
It would be nice if I could call something like:
jaydebeapi.connect("driver", [url, {'user':'username', 'password':'pass', 'more_parameters':'param'}], jars, libs)

**Comment by capdevc** [comment]
Looking forward to the attached PR getting merged. It's needed to access the new AWS Athena database via JDBC: "java.sql.SQLExceptionPyRaisable: java.sql.SQLException: property s3_staging_dir must be set"

**Comment by kenahoo** [comment]
Any chance of getting this merged?  I'm hitting the same issue.

**Comment by baztian** [comment]
Thanks testInord for your issue and the pull request which I really appreciate! Today I'm having a look at your PR.

I think the connection parameter api design you suggest needs some polishing. I hope to find a nice solution today or the next couple of days.
