### ISSUE TITLE
_to_date fails on dates before 1970.

### ISSUE THREAD

**Issue by kjwilder** [baztian/jaydebeapi#18]
I have some queries that are failing on dates before 1970 because of the following code in _to_date.
    d = datetime.datetime.strptime(str(java_val)[:10], "%Y-%m-%d")
    return d.strftime("%Y-%m-%d")
I am using the following fix:
    y, m, d = [int(x) for x in str(java_val)[:10].split('-')]
    return datetime.date(y, m, d)

**Comment by baztian** [comment]
Thanks. The problem should only apply to dates before 1900 and not 1970:

    >>> d = datetime.datetime.strptime(str('1900-1-1')[:10], "%Y-%m-%d")
    >>> d.strftime("%Y-%m-%d")
    '1900-01-01'

    >>> d = datetime.datetime.strptime(str('1899-12-31')[:10], "%Y-%m-%d")
    >>> d.strftime("%Y-%m-%d")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: year=1899 is before 1900; the datetime strftime() methods require year >= 1900

Your fix seems to do the trick!

**Comment by pepperblue** [comment]
Using Python 3.4 things are working with dates before year 1900 ...

**Comment by baztian** [comment]
Interestingly cx_oracle seems to suffer from the same python issue: https://stackoverflow.com/questions/40719511/the-datetime-strftime-methods-require-year-1900

**Comment by baztian** [comment]
I can't remember why I did implement it that complicated. I could just return

    str(java_val)[:10]

There might has been an issue with an oracle version. I have to check that first before merging a fix.
