### ISSUE TITLE
Running Python 3.8.2 and latest JDK (SE16), but jaydebeapi connection throws error about class file versions

### ISSUE THREAD

**Issue by GeneGeneGitHub** [baztian/jaydebeapi#197]
Trying to connect Python to an HSQLDB file-database (not in memory)

import jaydebeapi
conn = jaydebeapi.connect("org.hsqldb.jdbcDriver",
                           "jdbc:hsqldb:file:D:/computer/dev/HSQLDB/DBNAME/",
                           ["SA", "hogsdfs"],
                           "D:\\computer\\apps\\database\\HSQLDB\\hsqldb-2.6.0\\hsqldb\\lib\\hsqldb.jar",)

Traceback (most recent call last):                                                                                                                
  File "temphsqldb.py", line 2, in <module>                                                                                                      
    conn = jaydebeapi.connect("org.hsqldb.jdbcDriver",                                                                                           
  File "D:\computer\dev\python\3.8.2\lib\site-packages\jaydebeapi\__init__.py", line 412, in connect                                             
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)                                                                              
  File "D:\computer\dev\python\3.8.2\lib\site-packages\jaydebeapi\__init__.py", line 221, in _jdbc_connect_jpype                                 
    jpype.JClass(jclassname)                                                                                                                     
  File "D:\computer\dev\python\3.8.2\lib\site-packages\jpype\_jclass.py", line 99, in __new__                                                    
    return _jpype._getClass(jc)                                                                                                                  
java.lang.UnsupportedClassVersionError: java.lang.UnsupportedClassVersionError: org/hsqldb/jdbcDriver has been compiled by a more recent version 
of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Thrameos** [comment]
This issue is not with jaydebeapi nor with jpype, but the JVM version and the driver version.  The driver you are attempting to load is Java 11, but the JVM that you are using is Java 1.8.   Upgrade the Java version and it should work fine.

**Comment by GeneGeneGitHub** [comment]
$ java -version                              
java version "16.0.2" 2021-07-20                                          
Java(TM) SE Runtime Environment (build 16.0.2+7-67)                       
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

Same error:
java.lang.UnsupportedClassVersionError: java.lang.UnsupportedClassVersionError: org/hsqldb/jdbcDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Thrameos** [comment]
The issue is not the version of java executable, but rather the one that is being picked up by Python typically through JAVA_HOME.  If JAVA_HOME is not specified then it will search known paths and the registry.    I would recommend calling ``print(jpype.getDefaultJVMPath())`` and see what JVM it found.  On systems with multiple JVMs installed where the registry or paths find an old JVM first, you should point JAVA_HOME to the correct root directory.   Common user errors are to point JAVA_HOME to the bin or lib directory rather than the root.   In that case it will perform a search and likely find the old JVM.  Here is an example.

```
$ echo $JAVA_HOME
/usr/lib/jvm/java-14-openjdk-amd64
$ ls $JAVA_HOME
bin  conf  docs  include  jmods  legal  lib  man  release
$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
>>> jpype.startJVM()
>>> print(jpype.getDefaultJVMPath())
/usr/lib/jvm/java-14-openjdk-amd64/lib/server/libjvm.so
>>> print(jpype.java.lang.System.getProperty("java.version"))
14.0.2
```

**Comment by GeneGeneGitHub** [comment]
Thrameos,  You got it:

OLD
>>> print(jpype.getDefaultJVMPath())
C:\Program Files\Java\jre1.8.0_301\bin\server\jvm.dll
>>> print(jpype.java.lang.System.getProperty("java.version"))
1.8.0_301

$ setx -m JAVA_HOME "C:\Program Files\Java\jdk-16.0.2"
$ setx -m JRE_HOME "C:\Program Files\Java\jre1.8.0_301"

NEW
>>> print(jpype.getDefaultJVMPath())                         
C:\Program Files\Java\jdk-16.0.2\bin\server\jvm.dll          
>>> print(jpype.java.lang.System.getProperty("java.version"))
16.0.2                                                       


Python connection to HSQLDB is now working!

Wonder why the Java install doesn't set those env variables?

Thanks very much for the quick and detailed help.
