### ISSUE TITLE
Binaries for Windows (32-bit Python 3.4 or 3.5)?

### ISSUE THREAD

**Issue by GGillan** [baztian/jaydebeapi#20]
Tried first to pip install, then downloaded the wheel file and tried pip install on that, but both fail. Using Windows 10 with Python 3.4 32-bit installed, pip version 7.1.2. Have Visual Studio 2013 and Visual Studio 2015 installed.

Error reported as 
running build_ext
building '_jpype' extension
error: Microsoft Visual C++ 10.0 is required (unable to find vcvarsall.bat)

Is there a binary available for Windows? Or do you have some advice on getting through this error?

Thanks.
George

**Comment by wchatx** [comment]
Try this: http://www.lfd.uci.edu/~gohlke/pythonlibs/#jpype

**Comment by baztian** [comment]
Thanks @wchatx for the link. @GGillan it is a jpype issue to not provide proper windows binaries. [the jpype docs](https://github.com/originell/jpype/blob/master/doc/install.rst) mention to use anaconda to install binaries. I haven't tried this myself and would prefere binaries not requiring another dependecy.

I've created a jpype issue originell/jpype#204
