### ISSUE TITLE
Call Procedure with output parameters on JDBC IBM DB2

### ISSUE THREAD

**Issue by DeltaFox0018** [baztian/jaydebeapi#205]
Hello,
I am using jaydebeapi via python
I created a procedure on AS400 with 2 input parameters and 1 output

CREATE PROCEDURE Procedure (    
IN user CHAR(10),                    
IN psw CHAR(10) ,                
OUT error CHAR(1))                
LANGUAGE RPGLE                          
SPECIFIC JRAPOBJ.JRI01SV1SP            
NOT DETERMINISTIC                        
NO SQL                                  
CALLED ON
NULL INPUT                    
EXTERNAL NAME 'LIB/PROGRAM'        
PARAMETER STYLE GENERAL WITH NULLS

from SQL if I run the call CALL Procedure(user, psw, ?)
I return as a result the variable error with S or N based on whether the login is successful or not
Via in JDBC driver if I call with cursor.execute() works but I can’t recover the output data

If I make a cursor print.arraysize I return 1 instead cursor.rowcount I return 0

How do I do that?
Thank you

**Comment by 9icon** [comment]
Was looking for how to retrieve output parameters as well. Is this option now available?
