### ISSUE TITLE
BOOLEAN and BYTEINT data_types don't appear to be recognized properly

### ISSUE THREAD

**Issue by Mokubyow** [baztian/jaydebeapi#23]
Connecting to a Netezza database.

BOOLEAN column gets the following error:

`/usr/local/lib/python3.5/site-packages/jaydebeapi/__init__.py:250: UserWarning: No type mapping for JDBC type 'BIT' (constant value -7). Using None as a default type_code.
  "Using None as a default type_code." % (type_name, jdbc_type_const))`

BYTEINT column gets the following error:

`/usr/local/lib/python3.5/site-packages/jaydebeapi/__init__.py:250: UserWarning: No type mapping for JDBC type 'TINYINT' (constant value -6). Using None as a default type_code.
  "Using None as a default type_code." % (type_name, jdbc_type_const))`

**Comment by baztian** [comment]
Thanks @Mokubyow. Should be fixed now.
