### ISSUE TITLE
bug of multi thread

### ISSUE THREAD

**Issue by hutianlaix** [baztian/jaydebeapi#24]
as the test code, it works well, 
but when it run in not main thread like this:

`thread.start_new_thread(test, ())
`
the process crashed, (the test code run in test function)
i used try-except but also crash, even cannot get the erroe stack.

the last code line is "self._prep = self._connection.jconn.prepareStatement(operation)",
then i got the java error info,  why ??

---

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f6e65fb22e0, pid=116, tid=140112128227072

 JRE version: OpenJDK Runtime Environment (7.0_101) (build 1.7.0_101-mockbuild_2016_04_21_13_21-b00)
 Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
 Derivative: IcedTea 2.6.6pre01
 Distribution: CentOS release 6.7 (Final), package rhel-2.6.6.1.el6_7-x86_64 u101-b00
 Problematic frame:
 C  [_jpype.so+0x3a2e0]  JPJavaEnv::GetEnv(_JNIEnv**)+0x0

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /tmp/hs_err_pid116.log

 If you would like to submit a bug report, please include
 instructions on how to reproduce the bug and visit:
   http://icedtea.classpath.org/bugzilla
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by baztian** [comment]
jaydebeapi uses jpype to access java libraries. You have to import jpype and call `jpype.attachThreadToJVM()` inside your thread. Ideally you call it after jaydebeapi `connect()` has been executed. That guarantees you jpype is set up correctly.

I was thinking about a mechanism that enables automatic thread attachement in jaydebeapi. But I'm not sure if that's what everybody wants in any case. Furthermore I'm not sure if that's something *jpype* should do automatically.

**Comment by baztian** [comment]
I've just opened a jpype issue originell/jpype#203.
