### ISSUE TITLE
python.exe has stopped working

### ISSUE THREAD

**Issue by josephlee427** [baztian/jaydebeapi#28]
When using the databaselibrary library in robot, I tried connecting with jaydebeapi and when trying to connect to my db my python stops working

Is there any reason why this might be happening?

Even when not in robot and just making a python file where I try to connect to an HSQLDB, as soon as it tries to connect to it, the shell restarts

**Comment by baztian** [comment]
Jaydebeapi 1.0.0 introduced an API incompatibility. Check if the robot framework is compatible to the changed `connect` method
