### ISSUE TITLE
Improve support for DB types

### ISSUE THREAD

**Issue by baztian** [baztian/jaydebeapi#3]
https://github.com/joel-costigliola/assertj-db/issues/3 outlined a soultion for a more clever conversion of types. regis1512 is not using getObject. He uses getDate/getTime/getTimestamp depending on the java.sql.Type. This fixes the issues with Oracle's date. It could also be used for other types.

If I'm at it: Implement a mapping for BIGINT (http://stackoverflow.com/questions/26899595/jpype-and-jaydebeapi-returns-jpype-jclass-java-lang-long)

**Comment by baztian** [comment]
Should be fixed in https://github.com/baztian/jaydebeapi/tree/feature/improve-types-support. Comments welcome.

**Comment by dennisobrien** [comment]
Hi @baztian 

The link in the above comment doesn't work for me.  Was there a commit that fixed the BIGINT mapping issue?

thanks,
Dennis

**Comment by baztian** [comment]
You might confuse this issue with issue #6 Issue #3 is already fixed and merged in the current version and addresses date time conversions. #6 adresses big int . Please see the link I've posted there in my last comment.
Please report your success/failure in #6 and let me know which DB you are using. Thanks.
