### ISSUE TITLE
Error no matching overloads

### ISSUE THREAD

**Issue by neilhwatson** [baztian/jaydebeapi#30]
I'm getting an error and the docs haven't helped me. I'm not experienced in JAVA. What might the problem be, or how can I debug it?

    ./beeline-jdbc.py 
    
    CLASSPATH is :/usr/hdp/2.4.3.0-227/hadoop/conf:/usr/hdp/2.4.3.0-227/hadoop/lib/*:/usr/hdp/2.4.3.0-227/hadoop/.//*:/usr/hdp/2.4.3.0-227/hadoop-hdfs/./:/usr/hdp/2.4.3.0-227/hadoop-hdfs/lib/*:/usr/hdp/2.4.3.0-227/hadoop-hdfs/.//*:/usr/hdp/2.4.3.0-227/hadoop-yarn/lib/*:/usr/hdp/2.4.3.0-227/hadoop-yarn/.//*:/usr/hdp/2.4.3.0-227/hadoop-mapreduce/lib/*:/usr/hdp/2.4.3.0-227/hadoop-mapreduce/.//*::mysql-connector-java-5.1.37:mysql-connector-java-5.1.37-bin.jar:mysql-connector-java-5.1.37.zip:mysql-connector-java.jar:/usr/hdp/2.4.3.0-227/tez/*:/usr/hdp/2.4.3.0-227/tez/lib/*:/usr/hdp/2.4.3.0-227/tez/conf:/usr/hdp/current/hadoop-client/*:/usr/hdp/current/hive-client/lib/*:/usr/hdp/current/hadoop-client/client/*

    Traceback (most recent call last):
      File "./beeline-jdbc.py", line 18, in <module>
        , hivejar)
      File "/home/dev/lib/JayDeBeApi-1.0.0-py2.6.egg/jaydebeapi/__init__.py", line 380, in connect
        jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
      File "/home/dev/lib/JayDeBeApi-1.0.0-py2.6.egg/jaydebeapi/__init__.py", line 199, in _jdbc_connect_jpype
        return jpype.java.sql.DriverManager.getConnection(url, *dargs)
    RuntimeError: No matching overloads found. at native/common/jp_method.cpp:117

An the script:

    #!/usr/bin/env python

    import jaydebeapi
    import os

    principal='hive/dev15-namenode-01.example.com@example.COM'
    server='localhost'
    port=10000
    database='tsz'
    hivejar='/usr/hdp/current/hive-client/lib/hive-jdbc.jar'

    url=("jdbc:hive2://" + server + ":" + str(port) + "/default;principal="
        + principal + ";")

    print 'CLASSPATH is '+os.environ['CLASSPATH']

    c=jaydebeapi.connect("org.apache.hive.jdbc.HiveDriver", [ url, '', '']
        , hivejar)

    cursor=c.cursor()

**Comment by baztian** [comment]
Which jpype version are you using? Please try latest. Guess it's jpype1
0.6.3.

Am 09.02.2017 16:21 schrieb "Neil H Watson" <notifications@github.com>:

**Comment by neilhwatson** [comment]
I went over the docs again, and this time it worked. Here's an example for to imporove the readme.

#### Shell env:

    export CLASSPATH=$CLASSPATH:$(hadoop classpath):/usr/hdp/current/hadoop-client/*:/usr/hdp/current/hive-client/lib/*:/usr/hdp/current/hadoop-client/client/*

#### Python code:

    server   ='localhost'
    principal='hive/dev15-namenode-01.example.com@EXAMPLE.COM'
    port     =1000

    url=("jdbc:hive2://" + server + ":" + str(port)
        + "/default;principal=" + principal + ";")

    conn=jaydebeapi.connect("org.apache.hive.jdbc.HiveDriver", url)

#### Nice to have:

How to suppress warnings like this?

    17/02/09 13:48:24 INFO jdbc.Utils: Supplied authorities: localhost:10000
    17/02/09 13:48:24 INFO jdbc.Utils: Resolved authority: localhost:10000
    17/02/09 13:48:25 WARN util.NativeCodeLoader: Unable to load native-hadoop
    library for your platform... using builtin-java classes where applicable


`
