### ISSUE TITLE
Python 3.6 - Error message

### ISSUE THREAD

**Issue by aquawill** [baztian/jaydebeapi#32]
following the official tutor but got this message:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-b637bd5709db>", line 1, in <module>
    conn = jaydebeapi.connect("org.apache.hive.jdbc.HiveDriver",'jdbc:oracle:thin:@eu-tcs-l1.ad.navteq.com:1521:L1',['RDF_TWN_2015Q3', 'ntgdf'],'C:/Python36/hsqldb-2.2.8.jar',)
  File "C:\Python36\lib\site-packages\jaydebeapi\__init__.py", line 63, in connect
    port=25333, classpath=classpath, javaopts=javaopts, die_on_exit=True)
  File "C:\Python36\lib\site-packages\py4j\java_gateway.py", line 1952, in launch_gateway
    create_new_process_group=create_new_process_group)
  File "C:\Python36\lib\site-packages\py4j\java_gateway.py", line 304, in launch_gateway
    _port = int(proc.stdout.readline())
ValueError: invalid literal for int() with base 10: b''

**Comment by baztian** [comment]
Are you sure you are using jaydebeapi? Looking at the stacktrace leads me to the assumption you are using a fork called jaydebeapi3 which uses another technology stack. Please consider using the original jaydebeapi or post your issue in the fork's issue management system.
BTW: jaydebeapi is Python 3 and 2 compatible.

**Comment by aquawill** [comment]
Hi,

Thank you, I confirm I'm using jaydebeapi not jaydebeapi3, however I still got the error message:

Run this: conn = jaydebeapi.connect("org.hsqldb.jdbcDriver","jdbc:oracle:thin:@eu-tcs-l1.ad.here.com:1521:L1",["username", "password"],"C:\\Users\\guanlwu\\Desktop\\Python_src\\hsqldb-2.3.4\\hsqldb\\lib\\hsqldb.jar",)

error message
jpype._jexception.SQLExceptionPyRaisable: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@eu-tcs-l1.ad.here.com:1521:L1

could you please advise? Thank you.

**Comment by baztian** [comment]
Please escape the Backslashes in your classpath.

Am 21.02.2017 03:55 schrieb "aquawill" <notifications@github.com>:

**Comment by aquawill** [comment]
Hi, Thank you for the advice, however it's still not working. Could it be the problem on the server end?

>>>conn = jaydebeapi.connect("org.hsqldb.jdbcDriver","jdbc:oracle:thin:@eu-tcs-l1.ad.here.com:1521:L1",["RDF_TWN_161N0", "ntgdf"],"C:\\Users\\guanlwu\\Desktop\\Python_src\\hsqldb-2.3.4\\hsqldb\\lib\\hsqldb.jar",)


Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-b4403a58ae29>", line 1, in <module>
    conn = jaydebeapi.connect("org.hsqldb.jdbcDriver","jdbc:oracle:thin:@eu-tcs-l1.ad.here.com:1521:L1",["RDF_TWN_161N0", "ntgdf"],"C:\\Users\\guanlwu\\Desktop\\Python_src\\hsqldb-2.3.4\\hsqldb\\lib\\hsqldb.jar",)
  File "C:\Python36\lib\site-packages\jaydebeapi\__init__.py", line 380, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "C:\Python36\lib\site-packages\jaydebeapi\__init__.py", line 199, in _jdbc_connect_jpype
    return jpype.java.sql.DriverManager.getConnection(url, *dargs)
jpype._jexception.java.sql.SQLExceptionPyRaisable: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@eu-tcs-l1.ad.here.com:1521:L1

**Comment by baztian** [comment]
You are mixing an Oracle URL with a hsqldb driver., you need a Oracle
driver in your classpath

Am 21.02.2017 07:11 schrieb "aquawill" <notifications@github.com>:

**Comment by aquawill** [comment]
Thank you, it's working now.
