### ISSUE TITLE
using props option in connect throws AttributeError in Python 3

### ISSUE THREAD

**Issue by saffrydaffry** [baztian/jaydebeapi#36]
Fixed in my local version with simple if/else logic that uses dict.items() if no PY2:

```if props is not None:
        jprops = jpype.java.util.Properties()
        if PY2:
            for k, v in props.iteritems():
                jprops.put(k, v)
        else:
            for k, v in props.items():
                jprops.put(k, v)
```

**Comment by saffrydaffry** [comment]
Just realized my version of jaydebeapi is actually from a fork: `https://github.com/Melraidin/jaydebeapi#egg=jaydebeapi` and the current version doesn't have a `props` parameter.  Would this make more sense as a feature request?

I previously used jaydebeapi to connect to AWS Athena. This was straightforward with the props parameter which allows you to specify the required property 's3_staging_dir'.

**Comment by baztian** [comment]
Thank you. Which problem are you facing when not using your local version? Looking at [__init__.py](/baztian/jaydebeapi/blob/master/jaydebeapi/__init__.py) I don't see any calls to iteritems. Can you please also provide a stacktrace. That would be helpful.

**Comment by baztian** [comment]
Driver properties are supported since 1.0.0. Search for _An alternative way to establish connection using connection properties_ in the README.
