### ISSUE TITLE
Super slow SQL pulls against Teradata

### ISSUE THREAD

**Issue by melihozbek** [baztian/jaydebeapi#65]
My SQL queries are extremely slow against Teradata. So for example, a sample SQL pull takes 5 seconds with SQL Assistant or with R (using JDBC, the same driver that I use). The same pull takes about 10 times as long with this:

# ============================
import jaydebeapi as jdb
jclassname = 'com.teradata.jdbc.TeraDriver'
SERVER = '...'  # I know this is set correctly. 
t_url = "jdbc:teradata://" + SERVER
user = "..."
passwd = "..."
sql = "...."

conn = jdb.connect(jclassname=jclassname, url=t_url, driver_args=[user, passwd])
cursor = conn.cursor()
cursor.execute(sql)
dat = cursor.fetchall()
# =============================

It runs fine, but this will take about 40-50 seconds. I've tried everything, from using fetchone() instead of fetchall(), to changing the cursor.arraysize etc., but it's still extremely slow. I know the .jar files are fine, as R uses them to pull the same data in 5 seconds. Any ideas?

(I'm using Python 2.7.14, 64 bit and jaydebeapi 1.1.1)

**Comment by baztian** [comment]
Please find my answers regarding jaydebeapi performance on stackoverflow.com
https://stackoverflow.com/a/27211923/1960601

**Comment by melihozbek** [comment]
I've already tried those ideas, but it didn't really improve much. I've found out that pyodbc performs better, at least for my purposes. Thanks for your suggestions anyway.
