### ISSUE TITLE
Jaydebe makes first call but always errors on following

### ISSUE THREAD

**Issue by xXPhenomXx** [baztian/jaydebeapi#7]
I am running a Django 1.8.2 application on OSX,  trying to use the Jaydebeapi in order to query an IBM DB2 instance.

The first query will always work without a hitch but any following queries bomb with an error and I must restart Pycharm for it to work again.

conn = jaydebeapi.connect('com.ibm.as400.access.AS400JDBCDriver', ['jdbc:as400://TMCAS400:446', 'USERNAME', 'PASSWORD'], ['/Users/jassenmichaels/Library/Preferences/PyCharm40/jdbc-drivers/jt400.jar', '/Users/jassenmichaels/Library/Preferences/PyCharm40/jdbc-drivers/jtopen-driver-license.txt'])

ERROR:
<bound method java.sql.SQLExceptionPyRaisable.message of SQLExceptionPyRaisable(<jpype._jclass.java.sql.SQLException object at 0x10b3b54d0>,)> is not JSON serializable

I am using the same jars and config that PyCharm is using in its internal DB tools which work without issue and I can browse / query against this instance.

Any ideas on what I may be doing wrong?

**Comment by baztian** [comment]
Please provide more information about the error. "is not JSON serializable" doesn't come from Jaydebeapi. Do you have a Stacktrace? Can you show some code?
What do you mean by "first query"? Do you have to queries in one django request? What does the first query look like and what does the second look like?

**Comment by xXPhenomXx** [comment]
Sorry about that, the JSON portion of the error was due to how I was catching/sending back the error, here is the clean error I am seeing:
<bound method java.sql.SQLExceptionPyRaisable.message of SQLExceptionPyRaisable(<jpype._jclass.java.sql.SQLException object at 0x109a50cd0>

Via a form the user enters a serial number that triggers an AJAX call using an Angular service. The python method called is the following:

    def get_product_from_workorder(self, serial):
        """
        Fetch product number from serial

        :param serial: serial number
        :type serial: str.

        :return: JSON -- JSON result with product, workorder, and serial number
        :raises: Exception
        """
        try:
            # Get cursor object
            cursor = self.cursor

            # Parse serial to get Work Order
            serial = serial.split('-')
            wo = int(serial[0])

            # Query
            cursor.execute("SELECT * FROM V84MODSF.WO300ALL WHERE WRKNO = ? FETCH FIRST 1 ROW ONLY", (wo,))
            row = cursor.fetchone()

            # Get value stream
            cursor.execute("SELECT * FROM V84MODSF.MSPMLTM4 WHERE PRDNO = ? FETCH FIRST 1 ROW ONLY", (row[3].strip(),))
            row2 = cursor.fetchone()

            # Get the WO promise date
            cursor.execute("SELECT * FROM V84FILES.MFWOP100 WHERE RELNO = ? AND WRKNO = ? FETCH FIRST 1 ROW ONLY", (1, wo))
            row3 = cursor.fetchone()

            if row is None:
                return False
            else:
                return {'serial': serial, 'wo': wo, 'product': row[3].strip(), 'value': row2[31].strip(), 'promise': row3[8], 'size': row3[13]}

        except Exception as e:
            return False

So basically this method validates the serial, grabs some information about it and returns it.

Each time a serial is entered and the user TABS out of the field a new call is made.

Here is my init() for the database class I use to connect to DB2:

    def __init__(self):
        """
        Wrapper for IBM iSeries (TMCAS400)

        :return:
        """
        import pyodbc
        from django.conf import settings

        self.cursor = None
        state = getattr(settings, "DEBUG", None)

        # Check if record exists
        if state:
            conn = jaydebeapi.connect('com.ibm.as400.access.AS400JDBCDriver', ['jdbc:as400://TMCAS400:446', 'AUTOMATE', 'BCD01234'], ['/Users/jassenmichaels/Library/Preferences/PyCharm40/jdbc-drivers/jt400.jar', '/Users/jassenmichaels/Library/Preferences/PyCharm40/jdbc-drivers/jtopen-driver-license.txt'])
            # conn = pyodbc.connect('DSN=DB2;UID=AUTOMATE;PWD=BCD01234')
        else:
            conn = pyodbc.connect('DSN=DB2;UID=AUTOMATE;PWD=BCD01234')

        # Instantiate cursor object
        self.cursor = conn.cursor()

**Comment by baztian** [comment]
A stacktrace an a more specific error message would be very helpful. How do you know it fails at the second query? Can you run get_product_from_workorder without django?
For now I can't see why this is a jaydebeapi issue as it can be anything from wrong query over programming error to django issue.
BTW: For me it looks like you could optimize your queries into one or two using joins or subselects.

**Comment by baztian** [comment]
Please open this issue again if you're still facing the issue. But please provide some more information.
