### ISSUE TITLE
JayDeBeApi throws can't find the class org.postgresql.Driver

### ISSUE THREAD

**Issue by sgaseretto** [baztian/jaydebeapi#79]
I'm trying to establish a connection with postgres, but I'm getting this error all the time:
```
jpype._jexception.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class org.postgresql.Driver not found
```

I'm trying to stablish the connection this way
```
import jaydebeapi as jdbc

postgresql_class = 'org.postgresql.Driver'
postgresql_jdbc_path = './postgresql-42.2.4.jar'
postgresql_url = 'jdbc:postgresql://localhost:5432/database'
postgresql_user = 'user'
postgresql_pw = 'pass'

conn = jdbc.connect(postgresql_class, [postgresql_url, postgresql_user, postgresql_pw], postgresql_jdbc_path)
```
I tryied both the absolute and relative path, and I'm still getting this error. Does anyone have an idea of what could the problem be?

**Comment by sgaseretto** [comment]
I've just figured out what was the problem
the database url doesn't have to be inside the list with the username and password, it should be like this:
```
conn = jdbc.connect(pg_class, pg_url, [pg_user, pg_pw], pg_jdbc_path)
```

**Comment by mady143** [comment]
Hi @sgaseretto @baztian @Iverian @Thrameos @khangp0000 

from pyspark.sql import SparkSession
import findspark
import jaydebeapi
findspark.add_packages('mysql:mysql-connector-java:8.0.22')
spark = SparkSession.builder.appName('local').getOrCreate()
connection_String = 'jdbc:mysql://localhost:3306/employee?allowPublicKeyRetrieval=true&useSSL=false'
jdbc_driver_name='com.mysql.jdbc.Driver'
jarFile='C:\spark-2.3.4\jars\mysql-connector-java:8.0.22.jar'
username='admin'
password='admin123'
conn = jaydebeapi.connect(jclassname=jdbc_driver_name, url=connection_String, driver_args={'user': username, 'password': password},jars=jarFile)

my code is this but i am getting an error like TypeError: Class com.mysql.jdbc.Driver is not found

i was so confused can anyone help me to resolve this

Thanks and Regards,
Manikantha Sehar.

**Comment by khangp0000** [comment]
@mady143 
Based on my skimming, your jar path is not escaped correctly. Should be
`'C:\\spark-2.3.4\\jars\\mysql-connector-java:8.0.22.jar'`
I may be wrong though.

**Comment by digital-budisantoso** [comment]
jaydebeapi.connect('org.teiid.jdbc.TeiidDriver', 'jdbc:teiid:TCHS@mm://10.254.208.24:31000;version= ', ['usrtchs','gakum'], r'C:\SOTFWARE\drivers\teiid-jdbc-8.12.18.6_4-redhat-64-3.jar',) why errr
