### ISSUE TITLE
JayDeBeApi support with latest java versions

### ISSUE THREAD

**Issue by rohanmonteiro** [baztian/jaydebeapi#8]
Hi

Looks like JayDeBeApi supports only legacy Java 6. Are there plans to support Java 7, 8?

**Comment by baztian** [comment]
Hi, it definitely works with Java 7 and 8. See the testsuite results on [Travis ci](https://travis-ci.org/baztian/jaydebeapi). What are your concrete problems?

**Comment by rohanmonteiro** [comment]
When I connect to db via jaydebeapi with Java 8, it throws an error 
"To open "Python" you need to install the legacy Java SE 6 runtime"
I have set java_home variable and still throws the issue. When I install Java SE6 it works fine. I am on mac.

**Comment by baztian** [comment]
There is no such (strange) error message coming from JayDeBeApi. 
I might be able to give you a hint if you provide parts if the source where the Erie happens and a full stack trace. 
Sent from my Wiko GETAWAY

**Comment by rohanmonteiro** [comment]
Can this be used with jython only? or standalone python as well? May be the error is coming from something the api uses underneath. I am unable to get a full stack trace it just throws the above error, looks like it cant detect java . However when I run java -version I see it installed.

Below is the source
driver = 'org.postgresql.Driver'
server = 'xxx'
user = 'xxx'
pwd  = 'xxx'
database = '/Users/xxx/Downloads/postgresql-9.4-1201.jdbc4.jar'
conn = jd.connect(driver, [server, user, pwd],database)

**Comment by baztian** [comment]
As mentioned in jaydebeapi docs it is compatible with both, jython and python. In the python case you have to install Jpype in advance. What versions of jpype and jaydebeapi have you installed?
Does the code break art the connect method? Put some print statements before and after to find out our use the debugger.

**Comment by rohanmonteiro** [comment]
Yes I have installed JPype and it looks like the error is coming when starting up the jvm.

**Comment by rohanmonteiro** [comment]
Closing . This solution worked for me.
http://stackoverflow.com/questions/19563766/eclipse-kepler-for-os-x-mavericks-request-java-se-6/19594116#19594116
