### ISSUE TITLE
No matching overloads found for setProperty

### ISSUE THREAD

**Issue by warrenronsiek** [baztian/jaydebeapi#86]
I'm trying to connect to Redshift using IAM credentials, and I am getting an error `No matching overloads found for setProperty`. 

My connection string is: 
```
jaydebeapi.connect('com.amazon.redshift.jdbc.Driver',
                                 'jdbc:****/dev',
                                  driver_args={'AccessKeyId': aws_access_key_id,
                                               'SecretAccessKey': aws_secret_access_key,
                                               'SessionToken': session_token,
                                                'Iam': 1},
                                  jars='../RedshiftJDBC42-no-awssdk-1.2.15.1025.jar')
```
I've tried using RedshiftJDBC42-1.2.16.1027.jar and RedshiftJDBC42-no-awssdk-1.2.15.1025.jar. 

What is going wrong here?

**Comment by baztian** [comment]
Have you tried setting the iam property to a string value? I there is no overloaded method for int value properties.

**Comment by warrenronsiek** [comment]
Well, that changes the error. It is now saying that `Connection Refused: [Amazon][JDBC](11640) Required Connection Key(s): PWD, UID` so thats progress of a sort. Although, it still doesn't make sense, IAM authentication shouldn't need usernames and passwords.
