### ISSUE TITLE
JayDeBeApi works with Mimer

### ISSUE THREAD

**Issue by fernandezcuesta** [baztian/jaydebeapi#9]
Hi, FYI jaydebeapi works perfectly with Mimer DB version 10.0.7c running on OpenVMS 8.3.

    >>> jar = 'mimjdbc3.jar'
    >>> args='-Djava.class.path=%s' % jar
    >>> jvm = jpype.getDefaultJVMPath()
    >>> jpype.startJVM(jvm, args)
    >>> conn = jaydebeapi.connect('com.mimer.jdbc.Driver', ['jdbc:mimer://my_server:1360/MY_DB', 'USER', 'PASSWORD'])

Cheers

**Comment by baztian** [comment]
Cool, thanks!

**Comment by baztian** [comment]
Updated README.rst to mention Mimer DB compatibility.
